<?php
return [
	'sindom' => [
		'board_login' => env("BOARD_LOGIN"),
    	'board_pass' => env("BOARD_PASS"),
    	//POST для аутентификации
    	'post' => ('LoginForm[password]='.env("BOARD_PASS").'&LoginForm[rememberMe]=0&LoginForm[username]='.env("BOARD_LOGIN").'&yt0=Войти'),
    	//URL страницы логина
    	'loginurl' => ('http://sindom.ru/site/login.html'),
    	//Имя файла cookie
    	'cookiename' => ('cookie4sindom.txt'),
    	//Основная часть post запроса создания объявления
    	'postcr' => ("#=&Attr[attr_13]=&Classifieds[ads_user_name]=Магазин Подарков164&Classifieds[cid]=5005&Classifieds[coid]=3159&Classifieds[createStep]=2&Classifieds[fileProcessId]=b641e3900a&Classifieds[fiz_ur]=&Classifieds[images]=&Classifieds[phone]=252-088&Classifieds[reid]=4969&Classifieds[rid]=43&file=&yt0=Отправить"),
    	//Заголовок объявления в post запросе создания объявления 
    	'posttitle' => ("&Classifieds[title]="),
    	//Цена в post запросе создания объявления
    	'postprice' => ("&Classifieds[price]="),
    	//Тело объявления в post запросе создания объявления
    	'postdescr' => ("&Classifieds[contents]="),
    	//URL для создания объявления
    	'posturl' => ('http://sindom.ru/create.html'),
    	'editurlbegin' => ('<dl><dt></dt><a rel="'),
    	'editurlend' => ('" class="ajaxPhoneLink"'),
    	'editurl1' => ('http://saratov.sindom.ru/edit/'),
    	'editurl2' => ('.html'),
        'urlupload1' => ('http://saratov.sindom.ru/imager.html?fileProcessId=b641e3900a&id='),
        'urlupload2' => ('&PHPSESSID='),//$phpsessid
        'param1begin' => ('\'PHPSESSID\':\''),
        'param1end' => ('\',\'YII_CSRF_TOKEN\':\''),
        'urlupload3' => ('&YII_CSRF_TOKEN='),//$token
        'param2begin' => ('\'YII_CSRF_TOKEN\':\''),
        'param2end' => ('\',\'fileProcessId\''),
        'postdata' => [],
        'postdatafieldname' => ('qqfile'),
        'postdataidbegin' => ('"filename":"'),
        'postdataidend' => ('"}'),
        'postudimage' => ("#=&Attr[attr_13]=&Classifieds[ads_user_name]=Магазин Подарков164&Classifieds[cid]=5005&Classifieds[coid]=3159&Classifieds[createStep]=2&Classifieds[fileProcessId]=b641e3900a&Classifieds[fiz_ur]=&Classifieds[phone]=252-088&Classifieds[reid]=4969&Classifieds[rid]=43&file=&yt0=Отправить"),
    	'postudimglink' => ('&Classifieds[images]='),
	],
    'leboard' =>
    [
        'board_login' => env("BOARD_LOGIN"),
        'board_pass' => env("BOARD_PASS"),
        'post' => (''),
        //URL страницы логина
        'loginurl' => ('https://leboard.ru/auth/login'),
        //Имя файла cookie
        'cookiename' => ('cookie4leboard.txt'),
        //Основная часть post запроса создания объявления
        'postcr' => ("filefield=&filefield=&filefield=&category_id=108247&used=0&average_price=&phone=89172064405&city_id=498677&city_name=%D0%A1%D0%B0%D1%80%D0%B0%D1%82%D0%BE%D0%B2&latitude=51.54056000&longitude=46.00861000&autoanswer_text="),
        //Заголовок объявления в post запросе создания объявления 
        'posttitle' => ("&title="),
        //Цена в post запросе создания объявления
        'postprice' => ("&price="),
        //Тело объявления в post запросе создания объявления
        'postdescr' => ("&description="),
        //URL для создания объявления
        'posturl' => ('https://leboard.ru/post-web'),
        'editurlbegin' => ('href="https://leboard.ru/add/step3/'),
        //3127458
        'editurlend' => ('"><meta'),
        'editurl1' => ('https://leboard.ru/edit/'),
        'editurl2' => (''),
        'urlupload1' => ('https://leboard.ru'),
        'urlupload2' => (''),
        'param1begin' => ('data-url="'),
        'param1end' => ('" multiple'),
        'postdata' => [
                        'category_id' => '108247',
                        'used' => '0',
                        'price_type' => '0',
                        'auction-start-price' => '0',
                        'auction-max-price' => '0',
                        'auction-period' => '3',
                        'average_price' => '',
                        'phone' => '89172064405',
                        'city_id' => '498677',
                        'city_name' => '%D0%A1%D0%B0%D1%80%D0%B0%D1%82%D0%BE%D0%B2',
                        'latitude' => '51.54056000',
                        'longitude' => '46.00861000',
                        'autoanswer_text' => '',
                        ],  
        'postdatafieldname' => ('filefield'),
        'postdataidbegin' => ('"filename":"'),
        'postdataidend' => ('"}'),
        'postudimage' => ("filefield=&filefield=&filefield=&category_id=108247&used=0&average_price=&phone=89172064405&city_id=498677&city_name=%D0%A1%D0%B0%D1%80%D0%B0%D1%82%D0%BE%D0%B2&latitude=51.54056000&longitude=46.00861000&autoanswer_text="),
        'postudimglink' => ('&images[]='),
        'postudmainphoto' => ('&main_photo='),
    ],
    'divobazar' => [
        'board_login' => env("BOARD_LOGIN"),
        'board_pass' => env("BOARD_PASS"),
        'post' => ('email='.env("BOARD_LOGIN").'&pass='.env("BOARD_PASS").'&Submit=%C2%A0%C2%A0%D0%92%D0%BE%D0%B9%D1%82%D0%B8%C2%A0%C2%A0&MM_logn=logn'),
        'loginurl' => ('http://divobazar.ru/go/input.php'),
        'cookiename' => ('cookie4divobazar.txt'),
        'postcr' => [
                'region_0' => '2427',
                'name_reg_0' => 'Саратовская область',
                'region_1' => '7179',
                'name_reg_1' => '',
                'razdel_0' => '73',
                'razdel_1' => '221',
                'suff_b' => '',
                'pols[1]' => '1',
                'contakt[1]' => 'МАГАЗИН ПОДАРКОВ164',
                'email[1]' => 'magazinpodarkov164@yandex.ru',
                'tel[1]' => '89372252088',
                'map_x[1]' => '0',
                'map_y[1]' => '0',
                'adr' => '%D0%A1%D0%B0%D1%80%D0%B0%D1%82%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C',
                //'foto' => '',
                'comment[1]' => '0',
                'ip_address' => '',
                'id_catalog' => '',
                'add' => '1',
                'j_enabled' => '1',
                'submit' => 'Разместить объявление',
        ], 
        'posttitle' => ('zag[1]'),
        'postprice' => ("f_cena_[1]"),
        'postdescr' => ("opis_a"),
        'posturl' => ('http://divobazar.ru/blok/add.php'),
        'editurlbegin' => ('URL=\.\.'),
        'editurlend' => ('\'></HEAD>'),
        'editurl1' => ('http://divobazar.ru'),
        // 'editurl2' => (''),
        'urlupload1' => ('http://divobazar.ru/blok/upload_file_add.php'),
    ],
    'bonzon' => [
        'board_login' => env("BOARD_LOGIN"),
        'board_pass' => env("BOARD_PASS"),
        'post' => ('email='.env("BOARD_LOGIN").'&pass='.env("BOARD_PASS").'&Submit=%D0%92%D0%BE%D0%B9%D1%82%D0%B8&MM_logn=logn'),
        'loginurl' => ('http://bonzon.ru/user/logpass.php'),
        'cookiename' => ('cookie4bonzon.txt'),
        'postcr' => [
                'region_0' => '2427',
                'name_reg_0' => 'Саратовская область',
                'region_1' => '7179',
                'name_reg_1' => '',
                'razdel_0' => '73',
                'razdel_1' => '221',
                'suff_b' => '',
                'pols[1]' => '1',
                'contakt[1]' => 'МАГАЗИН ПОДАРКОВ164',
                'email[1]' => 'magazinpodarkov164@yandex.ru',
                'tel[1]' => '89372252088',
                'map_x[1]' => '0',
                'map_y[1]' => '0',
                'adr' => '%D0%A1%D0%B0%D1%80%D0%B0%D1%82%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C',
                //'foto' => '',
                'comment[1]' => '0',
                'ip_address' => '',
                'id_catalog' => '',
                'add' => '1',
                'j_enabled' => '1',
                'submit' => 'Разместить объявление',
        ], 
        'posttitle' => ('zag[1]'),
        'postprice' => ("f_cena_[1]"),
        'postdescr' => ("opis_a"),
        'posturl' => ('http://bonzon.ru/blok/add.php'),
        'editurlbegin' => ('URL=\.\.'),
        'editurlend' => ('\'></HEAD>'),
        'editurl1' => ('http://bonzon.ru'),
        // 'editurl2' => (''),
        'urlupload1' => ('http://bonzon.ru/blok/upload_file_add.php'),
    ],
    'rydo' => [
        'board_login' => env("BOARD_LOGIN"),
        'board_pass' => env("BOARD_PASS"),
        'post' => ('username='.env("BOARD_LOGIN").'&password='.env("BOARD_PASS").'&csrfmiddlewaretoken='),
        'loginurl' => ('http://rydo.ru/login/'),
        'cookiename' => ('cookie4rydo.txt'),
        'postcr' => [
                'location' => '2275',
                'category' => '88',
                'image[]' => '',
                'contact_email' => 'magazinpodarkov164@yandex.ru',
                'contact_phone' => '+7 (937) 225-20-88',
                'contact_skype' => '',
                'location_lat_long' => '',
                'location_adress' => '',
        ], 
        'posttitle' => ('title'),
        'postprice' => ("price"),
        'postdescr' => ("info"),
        'posturl' => ('http://rydo.ru/podat-obyavlenie/'),
        'editurl' => ('http://rydo.ru/profile/'),
        'editurlbegin' => ('Объявление не активно</span><a href="'),
        'editurlend' => ('" style'),
    ],
    '1000goods' => [
        'board_login' => env("BOARD_LOGIN"),
        'board_pass' => env("BOARD_PASS"),
        'post' => ('email='.env("BOARD_LOGIN").'&password='.env("BOARD_PASS").'&submit=%D0%92%D0%BE%D0%B9%D1%82%D0%B8+%D0%BD%D0%B0+%D1%81%D0%B0%D0%B9%D1%82'),
        'loginurl' => ('http://1000goods.ru/login/'),
        'cookiename' => ('cookie41000goods.txt'),
        'postcr' => [
                'location' => '3964',
                'gomodrilikus' => 'magazinpodarkov164@yandex.ru',
                'category' => '2142',
                'place' => '',
                'phone' => '+7 (937) 225-20-88',
                'name' => 'МАГАЗИН ПОДАРКОВ164',
                'email' => '',
                'pic2' => '',
                'pic3' => '',
                'pic4' => '',
                'upCode' => '<a href="http://saratov.1000goods.ru/prazdniki-i-podarki/originalnyje-podarki/" title="Сайт бесплатных объявлений «Оригинальные подарки» в Саратове"><img src="http://1000goods.ru/images/white.png" alt="Сайт бесплатных объявлений «Оригинальные подарки» в Саратове" /></a>',
                'linkType' => 'on',
                'upAdSite' => '',
        ], 
        'posttitle' => ('title'),
        'postprice' => ("price"),
        'postdescr' => ("description"),
        'posturl' => ('http://1000goods.ru/podat-obyavleniye/'),
        // 'editurl' => ('http://rydo.ru/profile/'),
        'editurlbegin' => ('location\.href=\''),
        'editurlend' => ('\';</script>'),
    ],
    'kuraga' => [
        'board_login' => env("BOARD_LOGIN"),
        'board_pass' => env("BOARD_PASS"),
        'post' => ('email='.env("BOARD_LOGIN").'&password='.env("BOARD_PASS").'&submit=%D0%92%D0%BE%D0%B9%D1%82%D0%B8+%D0%BD%D0%B0+%D1%81%D0%B0%D0%B9%D1%82'),
        'loginurl' => ('http://kuragi.net/login/'),
        'cookiename' => ('cookie4kuraga.txt'),
        'postcr' => [
                'location' => '3964',
                'gomodrilikus' => 'magazinpodarkov164@yandex.ru',
                'category' => '2142',
                'place' => '',
                'phone' => '+7 (937) 225-20-88',
                'name' => 'МАГАЗИН ПОДАРКОВ164',
                'email' => '',
                'pic2' => '',
                'pic3' => '',
                'pic4' => '',
                'upCode' => '<a href="http://saratov.kuragi.net/prazdniki-i-podarki/originalnyje-podarki/" title="Сайт бесплатных объявлений «Оригинальные подарки» в Саратове"><img src="http://kuragi.net/images/white.png" alt="Сайт бесплатных объявлений «Оригинальные подарки» в Саратове" /></a>',
                'linkType' => 'on',
                'upAdSite' => '',
        ], 
        'posttitle' => ('title'),
        'postprice' => ("price"),
        'postdescr' => ("description"),
        'posturl' => ('http://kuragi.net/podat-obyavleniye/'),
        // 'editurl' => ('http://rydo.ru/profile/'),
        'editurlbegin' => ('location\.href=\''),
        'editurlend' => ('\';</script>'),
    ],
    'gorodets' => [
        'board_login' => env("BOARD_LOGIN"),
        'board_pass' => env("BOARD_PASS"),
        'post' => ('login='.env("BOARD_LOGIN").'&password='.env("BOARD_PASS").'&a=login'),
        'loginurl' => ('http://tvoygorodets.ru/'),
        'cookiename' => ('cookie4gorodets.txt'),
        'urlupload' => ('http://tvoygorodets.ru/cms/modules/multiup/?field=info-image'),
        'postuploadimg' => [
            'info-parent' => '/board/drugoe',
            'parent' => '/board/drugoe/prodam',
            'info-contact' => 'Магазин',
            'info-contact-phone' => '89372252088',
            'info-contact-email' => 'magazinpodarkov164@yandex.ru',
            'info-period' => '30',
        ],
        'posttitle' => ('title'),
        'postprice' => ("info-price-value"),
        'postdescr' => ("brief"),
        'postcr' => [
            'info-parent' => '/board/drugoe',
            'parent' => '/board/drugoe/prodam',
            'info-contact' => 'Магазин',
            'info-contact-phone' => '89372252088',
            'info-contact-email' => 'magazinpodarkov164@yandex.ru',
            'info-period' => '30',
        ], 
        'posturl' => ('http://tvoygorodets.ru/personal/board/add.html?'),
        'editurlbegin' => ('canonical" href="'),
        'editurlend' => ('">'),
    ],
    'sar164' => [
        'board_login' => env("BOARD_LOGIN"),
        'board_pass' => env("BOARD_PASS"),
        'post' => ('login_login='.env("BOARD_LOGIN").'&login_password='.env("BOARD_PASS").'&login=true&login_button=%C2%EE%E9%F2%E8'),
        
        'loginurl' => ('http://saratov-164.ru/saratov-login'),
        'cookiename' => ('cookie4sar164.txt'),
        'urlupload' => ('http://saratov-164.ru/ajax/uploadphoto.ashx?fid=10&width=400&height=400&city=saratov'),
        'posttitle' => ('caption_text'),
        'postprice' => ("price"),
        'postdescr' => ("post_text"),
        'postcr' => [
            'user_phone' => '89372252088',
            'user_email' => 'magazinpodarkov164@yandex.ru',
            'ph' => 'saratov',
            'rb' => '',
            'apparel' => '1',
            'action' => '',
            'zx' => 'zx',
            'division' => '382',
            'city' => '773',
            'count' => '',
            'file' => '',
            'userType' => '1',
            'user_site' => 'http://magazinpodarkov164.ru/',
            'js-service_code' => 'free',
            'service_code' => 'free',
            'term-service' => 'on',
        ], 
        'posturl' => ('http://saratov-164.ru/saratov-podat-besplatnoe-obyavlenie/obyavleniya'),
        'editurlbegin' => ('og:url" content="http://'),
        'editurlend' => ('" />'),
    ],
    'itebe' => [
        'post' => ('dogs=in&log='.env("BOARD_LOGIN").'&pas='.env("BOARD_PASS2")),
        'loginurl' => ('https://itebe.ru/'),
        'cookiename' => ('cookie4itebe.txt'),
        'tokenurl' => ('https://itebe.ru/?do=new&product=3419&want=0&city=1771'),
        'tokenbegin' => ('data-token="'),
        'tokenend' => ('" data-gift'),
        'posttitle' => ('v[1]'),
        'posttitle2' => ('v[2]'),
        'postprice' => ("v[price]"),
        'postdescr' => ("v[text]"),
        'postcr' => [
            'dogs' => 'newgoods',
            'product' => '3419',
            'want' => '0',
            'city' => '1771',
            'img' => '3',
            'id' => '0',
            'f2' => '',
            'f3' => '',
            'v[price_ps]' => '0',
            'v[info]' => '1',
        ],
        'postaccept' => [
            'product' => '3419',
            'id' => '0',
            'want' => '0',
            'city' => '1771',
            'dogs' => 'recgoods',
        ],
        'posturl' => ('https://itebe.ru/'),
        'editurlbegin' => ('og:url" content = "'),
        'editurlend' => ('"/>'),
    ],
    'zpost' => [
        'post' => ('email='.env("BOARD_LOGIN").'&pass='.env("BOARD_PASS2")),
        'loginurl' => ('http://zoompost.ru/user/_vhod.php'),
        'cookiename' => ('cookie4zpost.txt'),
        'posttitle' => ('zag[1]'),
        'postprice' => ("f_cena_[1]"),
        'postdescr' => ("opis_a"),
        'postcr' => [
            'region_0' => '2427',
            'name_reg_0' => 'Саратовская область',
            'region_1' => '7179',
            'name_reg_1' => 'Саратов',
            'region_2' => '0',
            'name_reg_2' => '',
            'razdel_0' => '5',
            'razdel_1' => '33',
            'razdel_2' => '126',
            'suff_b' => '',
            'f_spisok_1[1]' => '5326',
            'pols[1]' => '1',
            'contakt[1]' => 'Магазин Подарков164',
            'email[1]' => 'magazinpodarkov164@yandex.ru',
            'tel[1]' => '89172064405',
            'url[1]' => '',
            'video_link[1]' => '',
            'map_x[1]' => '0',
            'map_y[1]' => '0',
            'adr' => '%D0%A1%D0%B0%D1%80%D0%B0%D1%82%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C%2C%20%20%D0%A1%D0%B0%D1%80%D0%B0%D1%82%D0%BE%D0%B2',
            'ip_address' => '',
            'id_catalog' => '',
            'add' => '1',
        ],
        'accepturl' => ('http://zoompost.ru/blok/add1.php'),
        'posturl' => ('http://zoompost.ru/blok/add.php'),
        'editurlbegin' => ('<a href="\.\.'),
        'editurlend' => ('" class="go">'),
    ],
    'apipost' => [
        'post' => ('email='.env("BOARD_LOGIN").'&pass='.env("BOARD_PASS2").'&Submit=%D0%92%D0%BE%D0%B9%D1%82%D0%B8+%D0%BD%D0%B0+%D1%81%D0%B0%D0%B9%D1%82&MM_logn=logn'), //Вынести логин в переменную
        'loginurl' => ('https://apipost.ru/obyavleniya/user/logpass.php'),
        'cookiename' => ('cookie4apipost.txt'),
        'posttitle' => ('zag[1]'),
        'postprice' => ("f_cena_[1]"),
        'postdescr' => ("opis_a"),
        'postcr' => [
            'region_0' => '60',
            'name_reg_0' => 'Саратовская область',
            'region_1' => '2911',
            'name_reg_1' => 'САРАТОВ',
            'razdel_0' => '7',
            'razdel_1' => '223',
            'suff_b' => '',
            'comment[1]' => '0',
            'pols[1]' => '1',
            'contakt[1]' => 'Магазин Подарков164',
            'email[1]' => 'magazinpodarkov164@yandex.ru',
            'tel[1]' => '+7 909 340 39 88',
            'skype[1]' => '',
            'video_link[1]' => '',
            'map_x[1]' => '0',
            'map_y[1]' => '0',
            'adr' => 'Саратовская область, САРАТОВ',
            'ip_address' => '',
            'id_catalog' => '',
            'add' => '1',
        ],
        'posturl' => ('http://apipost.ru/obyavleniya/blok/add.php'),
        'editurlbegin' => ('name="dop_kp" value="'),
        'editurlend' => ('">'),
        'linkbegin' => ('640px\)" href="'),
        'linkend' => ('" />'),
    ],
    'test' => [],
]

?>